# Site settings
title: Moamaoa
header-img: img/home-bg.jpg
email: endless3000@163.com
description: "三千止境 | 记录、分享和创造"
url: "http://moamaoa.com"
github_username:  moamaoa

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json"]
